project:
  type: book

book:
  title: "Treinamento COMP"
  author: "Alexandre Jaloto"
  date: "01/13/2025"
  chapters:
    - index.qmd
    - protocolo.qmd
    - banco_3pl.qmd
    - banco.sim.BIB.aberto.qmd
    - banco.sim.BIB.fechado.qmd

format:
  html:
    theme: cosmo
