# Banco 3PL

## Características do banco

O objeto `banco.sim.3PL` do pacote `INEPsico` contém dois elementos. O elemento `respostas` é um banco com 3.000 respostas e 45 itens de múltipla escolha. As respostas possíveis são "A", "B", "C", "D", "E", ".", "*". As respostas foram simuladas e todos os sujeitos responderam os 45 itens do instrumento. O elemento `gabarito` contém o gabarito dos 45 itens desse instrumento.

## Objetivo

Analisar o instrumento por meio da Teoria Clássica dos Testes (TCT) e Teoria de Resposta ao Item (TRI).

## Resumo das etapas de análise

1. Análise pela TCT (verificação da correlação bisserial do item e de possíveis inconsistências no gabarito)
2. Análise pela TRI (calibração, avaliação dos parâmetros, análise de DIF e análise de desajuste)

## Análise pela TCT

No pacote `INEPsico`, a análise é feita com a função `tct`. Caso você tenha dúvida sobre os argumentos, rode `?INEPsico::tct`. É preciso ter atenção com dois argumentos:

  * `alt`: o padrão da função é quatro alternativas e neste caso são cinco;
* `usa.normit`: o padrão da função é `TRUE` e para este caso deve-se usar `FALSE`, pois todas os sujeitos respondem os mesmos itens (e.g., não há BIB).

Após armazenar o resultado da TCT em um objeto, use a função `INEPsico::compara.sim.tct` para comparar seus resultados com o esperado.

## Análise pela TRI

### Rodada V0

A Rodada V0 é feita com todos os itens, a não ser que a equipe pedagógica tenha excluído algum. Não é o caso para este banco, então a próxima ação é a correção das respostas. Ou seja, as respostas devem ser dicotomizadas. Isso pode ser feito pela função `mirt::key2binary`.

É necessário configurar os valores iniciais e as distribuições prévias dos parâmetros. Uma forma de fazer isso é alterar a tabela de parâmetros, que é gerada com o argumento `pars = 'values'` da função `mirt::mirt`. Os valores das distribuições prévias são os mesmos do padrão do BILOG-MG. Neste programa, a média e o desvio da distribuição `log-normal` do parâmetro `a` são `1.0` e `1.64872127`, respectivamente. No pacote `mirt`, indica-se o logaritmo da média e do desvio. Portanto, os valores são `0` e `0.5`. Para o parâmetro `c`, que segue distribuição `beta`, o coeficiente alpha é obtido por `20*p+1` e o beta, por `20*(1-p)+1`, onde ‘p’ é o inverso do número de alternativas. Os demais argumentos para a função `mirt` são: `model = 1, TOL = 0.001, SE = TRUE, pars = par`, onde `par`corresponde à tabela de parâmetros gerada.

Para comparar os seus resultados com os oficiais, use `INEPsico::compara.sim.tri.v0`.

### Rodada V1

Para a Rodada V1, os itens com problemas de parâmetro, com DIF ou com ajuste ruim são excluídos. Neste livro, a Rodada V1 será feita após a exclusão conjunta de todos esses itens.

Os itens que atendam a pelo menos um dos seguintes critérios devem ser excluídos por problemas de parâmetro:
1. `a < 0.5`
2. `a > 4.0`
3. parâmetro b fora do intervalo de `–2.5 a 2.5`
4. `c > 0.45`

A análise de DIF e desajuste é feita com quatro métodos:
1. Maxadif (0,15) no intervalo entre P05 e P95;
2. RMSD;
3. MaxAjuste (0,15) no intervalo entre P05 e P95;
4. Regressão logística com tamanho de efeito (p < 0.05 & diferença do pseudo R2 > 0.035).

Os itens marcados por pelo menos um método são excluídos para a Rodada V1. A função `INEPsico::dif.mirt` faz essa análise.

Para comparar os seus resultados com os oficiais, use `INEPsico::compara.sim.tri.v1`.
