# Protocolo de análise

## Resumo das etapas de análise

Em geral, as análises possuem duas etapas:

1. Análise pela TCT (verificação da correlação bisserial do item e de possíveis inconsistências no gabarito)
2. Análise pela TRI (calibração, avaliação dos parâmetros, análise de DIF e análise de desajuste)

## Análise pela TCT

O objetivo é verificar inconsistências e problemas pedagógicos nos itens. Os itens que atendam a pelo menos um dos seguintes critérios devem ser recomendados para a revisão pedagógica:

1. correlação bisserial do gabarito  menor do que `0.30`
2. correlação de algum distrator maior do que `0.05`
3. discriminação (índice D) menor do que `0.20`

No pacote `INEPsico`, a análise é feita com a função `tct`. Caso você tenha dúvida sobre os argumentos, rode `?INEPsico::tct`.

Destaca-se que a análise é feita com o banco aberto. Ou seja, cada coluna do banco corresponde a um item e os sujeitos que não responderam ao item recebem `NA`. A função `INEPsico::abre.banco` gera um banco aberto.

Neste livro, o escore considerado na análise pela TCT corresponde à soma de acertos, ou seja, não se utiliza o normit.

Para comparar os seus resultados com os oficiais, use `INEPsico::compara.sim.tct`.

## Análise pela TRI

O objetivo da análise pela TRI é calibrar os itens novos na escala existente e calcular as notas dos sujeitos no caso de aplicação oficial.

### Rodada V0

Na Rodada V0, os itens com problema pedagógico e de bisserial são eliminados. Além disso, a tabela de parâmetros é gerada. Adotar o seguinte protocolo:

1. Eliminar itens excluídos pela equipe pedagógica
2. Alterar gabarito dos itens após indicação da equipe pedagógica
3. Eliminar  os itens com bisserial negativa (TCT somente com itens de múltipla escolha, IME)
4. Ordenar os itens de acordo com o seu bloco e posição no bloco (quando houver cadernos diferentes)
5. Dicotomizar as respostas dos IME. Isso pode ser feito pela função `mirt::key2binary`.
6. Ordenar o banco pela variável de identificação do sujeito
7. Recodificar os itens de resposta construída (IRC) de acordo com as orientações da equipe pedagógica
8. Configurar os valores iniciais e as distribuições prévias dos parâmetros.
a. Gere a tabela de parâmetros com o argumento `pars = 'values'` da função `mirt::mirt`
b. Altere os valores das distribuições prévias, que devem ser iguais aos do padrão do BILOG-MG. Nesse programa, a média e o desvio da distribuição `log-normal` do parâmetro `a` são `1.0` e `1.64872127`, respectivamente, na escala normal. O pacote `mirt` trabalha com a escala logística, em que a média é `1.7`. Além disso, nesse pacote, indica-se o logaritmo da média e do desvio. Portanto, os valores são `0.53062825106217`, que corresponde a `log(1.7)`, e `0.5`, que corresponde a `log(1.64872127)`. Para o parâmetro `c`, que segue distribuição `beta`, o coeficiente alpha é obtido por `20*p+1` e o beta, por `20*(1-p)+1`, onde ‘p’ é o inverso do número de alternativas. Em todas as análises serão utilizados os valroes para cinco alternativas. Assim, os valores devem ser:

| Variável    | a                         | g (c)             |
|:-----------:| :------------:            |:------------:     |
| prior.type  | 'lnorm' (lognrmal)        | 'expbeta' (beta)  |
| prior_1     | 0.53062825106217 (média)  | 5 (alpha)         |
| prior_2     | 0.5 (desvio padrão)       | 17 (beta)         |
| value       | 1.7                       | 0.2               |
| lbound      | 0                         | 0                 |
| ubound      |Inf                        | 1                 |

c. Caso haja itens comuns a uma aplicação anterior, seus parâmetros devem ser fixados. Para isso, substitua os parâmetros iniciais pelos valores a serem fixados e defina `est = FALSE` para esses itens.
9. Declarar os demais argumentos para a função `mirt`: `model = 1, TOL = 0.001, pars = par`, onde `par` corresponde à tabela de parâmetros gerada.
10. Incluir o tipo de item com o argumento `itemtype`. Para itens dicotômicos (IME), adotar `3PL`. Para itens politômicos (IRC), adotar `graded`.

Para comparar os seus resultados com os oficiais, use `INEPsico::compara.sim.tri.v0`.

### Rodada V1

Na Rodada V1, os itens com problemas de parâmetro, com DIF ou com ajuste ruim são excluídos. Neste livro, a Rodada V1 é feita após a exclusão conjunta de todos esses itens. Adotar o seguinte protocolo:

1. Excluir os itens *novos* com algum problema de parâmetros. Esses itens são os que atendem a pelo menos um dos seguintes critérios:
a. `a < 0.5`
b. `a > 4.0`
c. todos os parâmetros `b` fora do intervalo de `–2.5 a 2.5`
d. `c > 0.45`
2. Excluir os itens com problema de ajuste. O ajuste é calculado pelo método do RMSD. Valores acima de 0.10 são adotados como ponto de corte neste livro. No pacote `INEPsico`, o método é implementado pela função `dif.mirt`, que retorna os itens com problema no elemento `rmsd.pisa`. Quando o item é novo, a qualidade da calibração será avaliada pelo RMSD. Quando o item é comum, essa medida será usada para verificar se há DIF. Se um item novo tiver problema de ajuste, ele deve ser excluído. Se um item comum tiver problema de ajuste, ele deve ser recalibrado (`est = TRUE`).
4. A exclusão do item deve ser feita atribuindo-se `a=0` e `est=FALSE` na tabela de parâmetros para os itens excluídos
5. Rodar novamente a V1 até que não haja itens com problemas

Para comparar os seus resultados com os oficiais, use `INEPsico::compara.sim.tri.v1`.
